---
title: "Air Quality and Health in NYC"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
    code_folding: hide
---

### NYC Air Quality Estimation and Respitory disease risk due to air pollutants 

## Introduction 

Public health and overall community well-being are impacted by environmental factors such as the quantity of air pollutants in an area. Key pollutants of public health concern include: carbon monoxide (CO), ozone (O3), nitrogen dioxide(NO2), particulate matter (PM), and sulfur dioxide (SO2) [1](https://www.who.int/health-topics/air-pollution#tab=tab_1). Air pollution is associated with a number of health concerns such as respiratory diseases and heart attacks [2](https://www.epa.gov/report-environment/air#:~:text=Air%20pollution%2C%20whether%20indoors%20or,respiratory%20symptoms%2C%20and%20premature%20mortality.). According to the New York State Department of Heath, in-taking levels PM_2.5 can increase the risk for health problems [3](https://www.health.ny.gov/environmental/indoors/air/pmq_a.htm). 

The need for a comprehensive analysis and sustainable solutions for the increase of air pollutants is needed. The motivation behind this project stems from the potential effects pollutants may have on human health. We aim to understand the association between air quality and public health in New York City, to identify where interventions are needed. 

Our initial questions included: What are the air quality levels in New York City?, Which areas in New York City have more prominent air pollutants? How is air quality associated to the incidence of respiratory diseases in an area?







READ______[6](https://pubs.acs.org/doi/10.1021/acs.est.0c00694). 


## Methods 

Data: Source, scraping method, cleaning, etc.
Improvement Ratio [7](https://www.sciencedirect.com/science/article/pii/S0013935120314523?via%3Dihub)
Exploratory analysis: 
Additional analysis: 

## Results 

Exploratory analysis: 
Additional analysis: 

## Discussion and Conclusions
What were your findings? 
Are they what you expect? 
What insights into the data can you make?
Limitations? 
Future implications? 



-info on PM2.5 and previous findings-
-compare result to findings- 
PM2.5, a prevalent air pollutant, originates from both outdoor and indoor environments.Outdoor sources comprise of vehicle emissions, gas, and fires, while indoor contributors encompass tobacco smoke, candle combustion, and oil lamps [3](https://www.health.ny.gov/environmental/indoors/air/pmq_a.htm). Ambient PM2.5 attributed deaths increased from 3.5 million in 1990 to 4.2 million in 2015. In 2015, the fifth-ranking cause of global deaths was ambient PM2. [4](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5439030/). In a study following the PM2.5 concentration in NYC from 2015-2020, similar decrease levels between January and May were observed. There was less air pollutant in 2020 that could have been due to the government shutdown during the corona virus pandemic could not be confirmed. [5](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7314691/#bb0010). 
