---
title: "Data Sources"
output: 
  html_document:
    toc: true
    toc_float: true
---

This project uses publicly available data from multiple sources in its analysis.We initially used one air quality dataset and an accompanying hospitalization dataset, but we later added a shape dataset for more robust location data, another air quality dataset with daily observations and another hospitalization dataset with more information on respiratory hospitalizations.

## New York City Air Quality Datasets

Since 2008, the City of New York has actively maintained a dataset of up to date air quality information across most neighborhoods in the city. Accessible [here](https://data.cityofnewyork.us/Environment/Air-Quality/c3uy-2p5r), the raw data has measurements of certain air pollutants including nitrogen dioxide (NO2), ozone (O3) and fine particles (PM2.5). The dataset also contains some general information about vehicle traffic, air-pollutant related hospitalizations and more. The raw dataset from this source is named `air_quality.csv` in `data/raw_data`. We later added a dataset containing information on New York air quality at the daily level which is accessible [here](https://www.epa.gov/outdoor-air-quality-data/download-daily-data). This data has daily observations for a limited number of locations, making it ideal for a focused analysis on single zip codes/neighborhoods. The raw csv from this source is named `alt_air_data.csv` in `data/raw_data`. Shapefiles, available [here](https://github.com/nycehs/NYC_geography/tree/master/UHF_42_DOHMH_2009), were used to plot values into maps, and to join this data with the dataset with daily observations.


## Disease Datasets

Health data was first extracted from [NYC OpenData](https://data.cityofnewyork.us/Health/Emergency-Department-Visits-and-Admissions-for-Inf/2nwg-uqyg). This dataset starts on March 1, 2020 until November 30, 2022, and contains counts of emergency department visits, admissions and visits related to influenza-like and/or pneumonia illness, categorized by the modified ZIP code and date. For this dataset, influenza-like illness is defined as one or more of the following: a. fever AND cough; b. fever AND sore throat; c. mention of influenza). This health data was further supplemented by a public dataset, actively updated by the City of New York, containing the count of hospitalizations due to asthma, diarrhea, influenza-like illness, respiratory diseases and vomit for each zip code in NYC. Data collection began in 2016 and was last updated in early 2023. The data can be viewed [here](https://a816-health.nyc.gov/hdi/epiquery/visualizations?PageType=ps&PopulationSource=Syndromic) and subsets of the data can be selected and downloaded for use. These two files are named `disease_hospital_admin.csv` and `joined_respiratory.csv` respectively in `data/raw_data`. Both of these datasets were trimmed outside of the github repo prior to being pushed as they were too large to manipulate.


## Zip Code Datasets

Sometimes, we needed additional information about the zip codes: where the center of a zip code was, what neighborhood a zip code belonged to, and mapping projection information, among other things. Information on zip codes was found [here](https://github.com/erikgregorywebb/nyc-housing/blob/master/Data/nyc-zip-codes.csv), while zip code shapefiles were found [here](https://catalog.data.gov/dataset/tiger-line-shapefile-2019-2010-nation-u-s-2010-census-5-digit-zip-code-tabulation-area-zcta5-na). 