---
title: "Data Processing"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(tidyverse)
library(plotly)
options(readr.show_col_types = FALSE)
```

# Merging `joined_respiratory.csv` and `air_quality_disease.csv`

````{r, message = FALSE}
# Load dataset with respiratory and asthma counts (missing some zipcodes)

dis_asth_df = read_csv("data/cleaned_data/joined_respiratory.csv") |> 
  filter(zip != 88888 & zip != "Citwide" & age_group == "All age groups") |> 
  mutate(date = as.Date(format(as.Date(date, "%m/%d/%y"))),
         year = as.numeric(format(date, format = "%Y")),
         month = month.name[as.numeric(format(date, format = "%m"))],
         day = as.numeric(format(date, format = "%d")),
         zip = as.numeric(zip)) |>
  select(year, month, day, zip, count_resp, count_asth) 

# Load dataset with pneumonia data

dis_pneu_df = read_csv("data/raw_data/disease_hospital_admin.csv") |> 
  separate(date, into=c("month", "day", "year")) |> 
  mutate(day = as.numeric(day),
         month = month.name[as.numeric(month)],
         year = as.numeric(year)) |> 
  rename(zip = mod_zcta) |> 
  select(year, month, day, zip, total_ed_visits, ili_pne_visits, ili_pne_admissions)

# Merge two disease datasets

all_dis_df =
  full_join(dis_asth_df, dis_pneu_df, by = c("month", "day", "year", "zip"))

# Now merge disease with air quality dataset

air_qual_df = read_csv("data/cleaned_data/alt_air_data.csv") |> 
  separate(date, into=c("month", "day", "year")) |>
  mutate(day = as.numeric(day),
         month = month.name[as.numeric(month)],
         year = as.numeric(year)) |> 
  filter(!(year == '2020' & month == 'January'),
         !(year == '2020' & month == 'February')) |> 
  rename(zip = zip_code) |> 
  select(year, month, day, zip, pollutant, value) |> 
  group_by(day, month, year, zip, pollutant) |> 
  summarize(value = mean(value))

# air_qual_df_aqi = read_csv("data/cleaned_data/alt_air_data.csv") |> 
#   separate(date, into=c("month", "day", "year")) |>
#   mutate(day = as.numeric(day),
#          month = month.name[as.numeric(month)],
#          year = as.numeric(year)) |> 
#   filter(!(year == '2020' & month == 'January'),
#          !(year == '2020' & month == 'February'),
#          !(aqs_parameter_desc == "Acceptable PM2.5 AQI & Speciation Mass")) |>  
#   rename(zip = zip_code) |> 
#   select(year, month, day, zip, daily_aqi_value, pollutant, value) |> 
#   group_by(day, month, year, zip, pollutant) |> 
#   summarize(daily_aqi = mean(daily_aqi_value))

### note: removed acceptable pm2.5... from https://www.epa.gov/aqs/aqs-memos-technical-note-reporting-pm25-continuous-monitoring-and-speciation-data-air-quality

# Finally merge disease and air qual data together

air_qual_dis = # with value
  full_join(all_dis_df, air_qual_df, by = c("month", "day", "year", "zip")) |>  
  mutate(
    numeric_month = match(month, month.name),
    date = as.Date(paste(year, numeric_month, day, sep = "-"), format = "%Y-%m-%d")
  ) |> 
  select(year, month, day, date, zip, count_resp, count_asth, total_ed_visits, 
         ili_pne_visits, ili_pne_admissions, pollutant, value) |> 
  pivot_wider(names_from = pollutant,
              values_from = value) |> 
  select(-`NA`) |> 
  rename(pm25_ug_m3_lc = PM2.5,
         co_ppm = CO,
         o3_ppm = Ozone,
         no2_ppb = NO2) |> 
  filter(!(year == '2022' & month == 'December')) 


  
# air_qual_dis_aqi = # with daily aqi value
#   full_join(all_dis_df, air_qual_df_aqi, by = c("month", "day", "year", "zip")) |> 
#   select(year, month, day, zip, count_resp, count_asth, total_ed_visits, 
#          ili_pne_visits, ili_pne_admissions, pollutant, daily_aqi) |> 
#   pivot_wider(names_from = pollutant,
#               values_from = daily_aqi) |> 
#   select(-`NA`) |> 
#   rename(pm25_ug_m3_lc = PM2.5,
#          co_ppm = CO,
#          o3_ppm = Ozone,
#          no2_ppb = NO2) |> 
#   filter(!(year == '2022' & month == 'December')) |> 
#   mutate(
#     numeric_month = match(month, month.name),
#     date = as.Date(paste(year, numeric_month, day, sep = "-"), format = "%Y-%m-%d")
#   )

# measurement: ozone (daily_max_8_hour_ozone_concentration)
# co (daily_max_8_hour_co_concentration)
# pm2.5 (daily_mean_pm2_5_concentration)
# no2 (daily_max_1_hour_no2_concentration)
```

# Compare two air quality datasets (daily vs. seasonal/annual)

```{r, eval = F}
airqual_annual = read_csv("data/cleaned_data/uhf_airquality.csv") |> 
  filter(str_detect(name, "Fine") | str_detect(name, "NO2") | str_detect(name, "O3")) 

#### Prepare dataset from daily data (Summer: 1June-31Aug, Winter 1Dec-28Feb)

# Annual averages for each pollutant and each zip

airqual_yr_avg = air_qual_df |> 
  group_by(year, zip, pollutant) |> 
  summarize(mean = mean(value)) |> 
  pivot_wider(
    names_from = pollutant,
    values_from = mean
  )

# Seasonal averages for each pollutant and each zip

airqual_szn_avg = air_qual_df |> 
  mutate(season = case_when(
    month %in% c("June", "July", "August") ~ "summer",
    month %in% c("December", "January", "February") ~ "winter",
    TRUE ~ "other"
  )) |> 
  filter(season != "other") |> 
  group_by(season, year, zip, pollutant) |> 
  summarize(mean = mean(value)) |> 
  pivot_wider(
    names_from = pollutant,
    values_from = mean
  )

#### Prepare dataset from daily data

airqual_annual = read_csv("data/cleaned_data/uhf_airquality.csv") |> 
  filter(str_detect(name, "Fine") | str_detect(name, "NO2") | str_detect(name, "O3")) |> 
  select(name, )

#### Comparison between daily data and yearly/seasonal data

```


# Investigating the lagged association of Ozone with variables related to respiratory diseases

## Cross correlation analysis

```{r, out.width='100%', results = 'hide'}
ccf_df = air_qual_dis |> 
  filter(!is.na(o3_ppm) & !is.na(ili_pne_visits)) |> 
  mutate(date_lag = date + days(125),
         scaled_o3 = o3_ppm * 100, 
         lagged_pne = lag(ili_pne_visits, n = 125)
  )

ccf_res = ccf(ccf_df$o3_ppm, ccf_df$ili_pne_visits, lag.max=250, plot = FALSE)
plot(ccf_res, main = "Analysing Lag between Ozone and Pneumonia ER visits (in days)")

# Visualize lag

ccf_df |> 
  ggplot() +
  geom_point(aes(x = date_lag, y = lagged_pne, color = "Pneumonia ER visits")) +
  geom_point(aes(x = date, y = scaled_o3, color = "Ozone (10^-2 ppm)")) +
  labs(title = "Lagging Pneumonia ER visits by 125 days", 
       x = "Date",
       y = "Values") +
  scale_color_manual(labels = c("Ozone (10^-2 ppm)", "Pneumonia hospital visits"), 
                     values = c("Ozone (10^-2 ppm)" = "#FFA500", "Pneumonia ER visits" = "#6495ED"), 
                     guide = "legend")

prelag_model = lm(ili_pne_visits ~ scaled_o3, data = ccf_df)
broom::tidy(prelag_model)
ggplot(aes(x = scaled_o3, y = ili_pne_visits), data = ccf_df) + 
  geom_point(color = "#FFA500") +
  geom_smooth(method = "lm", color = "blue") +
  labs(title = "Pre-lag: Pneumonia ER visits vs. Ozone",
       x = expression(paste("Ozone (", 10^-2, " ppm)")), 
       y = "Pneumonia hospital visits (count)")

lag_model = lm(lagged_pne ~ scaled_o3, data = ccf_df)
broom::tidy(lag_model)
ggplot(aes(x = scaled_o3, y = lagged_pne), data = ccf_df) + 
  geom_point(color = "#FFA500") +
  geom_smooth(method = "lm", color = "blue") +
  labs(title = "Post-lag: Pneumonia ER visits vs. Ozone",
       x = expression(paste("Ozone (", 10^-2, " ppm)")), 
       y = "Pneumonia hospital visits (count)")
```























```{r, eval = F, message = FALSE}
# EDA

## Histograms
ggplot(aes(x = date), data = air_qual_dis) +
  geom_point(aes(y = co_ppm, color = "CO"), size = 1) +
  geom_point(aes(y = o3_ppm, color = "O3"), size = 1) +
  labs(x = "Date", y = "Pollutant Level", color = "Pollutant") +
  scale_color_manual(values = c("PM2.5" = "blue", "CO" = "green", "O3" = "red", "NO2" = "purple")) +
  theme_minimal()

ggplot(aes(x = date), data = air_qual_dis) +
  #geom_point(aes(y = pm25_ug_m3_lc, color = "PM2.5"), size = 1) +
  #geom_point(aes(y = co_ppm, color = "CO"), size = 1) +
  geom_point(aes(y = o3_ppm, color = "O3"), size = 1) +
  #geom_point(aes(y = no2_ppb, color = "NO2"), size = 1) +
  labs(x = "Date", y = "Pollutant Level", color = "Pollutant") +
  scale_color_manual(values = c("PM2.5" = "blue", "CO" = "green", "O3" = "red", "NO2" = "purple")) +
  theme_minimal()


ggplot(aes(x = pm25_ug_m3_lc), data = air_qual_dis) + geom_histogram() 
ggplot(aes(x = co_ppm), data = air_qual_dis) + geom_histogram() 
ggplot(aes(x = o3_ppm), data = air_qual_dis) + geom_histogram() 
ggplot(aes(x = no2_ppb), data = air_qual_dis) + geom_histogram() 
ggplot(aes(x = sqrt(total_ed_visits)), data = air_qual_dis) + geom_histogram() 

ggplot(aes(x = ili_pne_visits), data = air_qual_dis) + geom_histogram() 
ggplot(aes(x = ili_pne_admissions), data = air_qual_dis) + geom_histogram() 

MASS::boxcox(lm(total_ed_visits ~ 1, data = air_qual_dis))



model1 = lm(count_resp ~ pm25_ug_m3_lc+co_ppm+o3_ppm+no2_ppb, data = air_qual_dis_aqi)
summary(model1)
model2 = lm(count_asth ~ pm25_ug_m3_lc+co_ppm+o3_ppm+no2_ppb, data = air_qual_dis_aqi)
summary(model2)
model3 = lm(total_ed_visits ~ pm25_ug_m3_lc+co_ppm+o3_ppm+no2_ppb, data = air_qual_dis_aqi)
summary(model3)
model4 = lm(ili_pne_visits ~ pm25_ug_m3_lc+co_ppm+o3_ppm+no2_ppb, data = air_qual_dis_aqi)
summary(model4)
model5 = lm(ili_pne_admissions ~ pm25_ug_m3_lc+co_ppm+o3_ppm+no2_ppb, data = air_qual_dis_aqi)
summary(model5)
base_model = lm(total_ed_visits ~ pm25_ug_m3_lc, data = air_qual_dis_aqi)

model = base_model |> MASS::stepAIC(direction = "both", trace = 0)
summary(model)

model1 |> ggplot(aes(x = pm25_ug_m3_lc, y = total_ed_visits)) + geom_point()
```


```{r, eval = F, message = FALSE}
# Old code
library(tidyverse)

# Load dataset with respiratory and asthma counts
dis_df = read_csv("data/cleaned_data/joined_respiratory.csv") |> 
  filter(zip != 88888 & zip != "Citwide" & age_group == "All age groups") |> 
  mutate(date = as.Date(format(as.Date(date, "%m/%d/%y"))),
         year = as.numeric(format(date, format = "%Y")),
         month = month.name[as.numeric(format(date, format = "%m"))],
         day = as.numeric(format(date, format = "%d")),
         zip = as.numeric(zip)) |>
  select(-date, -age_group)

# Load cleaned air quality dataset that has been merged with disease
air_dis_df = read_csv("data/cleaned_data/air_quality_disease.csv") |> 
  rename(zip = zip_code) |> 
  mutate(day = as.numeric(day)) |> 
  select(year, month, day, zip, total_ed_visits, ili_pne_visits, ili_pne_admissions, everything())

# Merge two datasets
all_dis_df =
  left_join(air_dis_df, dis_df, by = c("month", "day", "year", "zip")) |> 
  select(year, month, day, zip, total_ed_visits, ili_pne_visits, ili_pne_admissions, count_resp, count_asth, everything())

# Realized many NAs, suspect zipcode and date NAs
checkdate_perzip_airdis = airqual_annual |> 
  group_by(geo_place_name) |> 
  summarize(count = n())

checkdate_perzip_dis = dis_df |> 
  group_by(zip) |> 
  summarize(count = n())

# Load cleaned air quality dataset that has been merged with disease
air_dis_df = read_csv("data/cleaned_data/air_quality_disease.csv") |> 
  rename(zip = zip_code) |> 
  mutate(day = as.numeric(day)) |> 
  select(year, month, day, zip, total_ed_visits, ili_pne_visits, ili_pne_admissions, everything())

# Found many NAs in air_quality_disease.csv - need revision
```


