---
title: "Exploratory Analysis and Visualizations"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
    code_folding: hide
---

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(leaflet)
library(plotly)
options(readr.show_col_types = FALSE)
```

# Air quality EDA

```{r, eval = FALSE}
df_histo_pm2.5 = 
  read_csv("data/cleaned_data/air_quality_zips.csv") |> 
  mutate(zip = as.factor(zip)) |>
  filter(str_detect(time_period, "Annual Average")) |> 
  mutate(year = str_extract(time_period, "\\d{4}")) |> 
  filter(name == "Fine particles (PM 2.5)") |> 
  select(year, data_value)

df_histo_NO2 = 
  read_csv("data/cleaned_data/air_quality_zips.csv") |> 
  mutate(zip = as.factor(zip)) |>
  filter(str_detect(time_period, "Annual Average")) |> 
  mutate(year = str_extract(time_period, "\\d{4}")) |> 
  filter(name == "Nitrogen dioxide (NO2)") |> 
  select(year, data_value) 

df_histo_ozone =
  read_csv("data/cleaned_data/air_quality_zips.csv") |> 
  filter(name == "Ozone (O3)") |> 
  filter(str_detect(time_period, "2009|2010|2011|2012|2013|2014|2015|2016|2017|2018|2019|2020|2021")) |> 
  mutate(year = str_extract(time_period, "\\d{4}")) |> 
  select(year, data_value)
```

```{r}
df_histo_pm2.5 = 
  read_csv("data/cleaned_data/uhf_airquality.csv") |> 
  filter(str_detect(time_period, "Annual Average")) |> 
  mutate(year = str_extract(time_period, "\\d{4}")) |> 
  filter(name == "Fine particles (PM 2.5)") |> 
  select(year, data_value)

df_histo_NO2 = 
  read_csv("data/cleaned_data/uhf_airquality.csv")  |> 
  filter(str_detect(time_period, "Annual Average")) |> 
  mutate(year = str_extract(time_period, "\\d{4}")) |> 
  filter(name == "Nitrogen dioxide (NO2)") |> 
  select(year, data_value) 

df_histo_ozone =
  read_csv("data/cleaned_data/uhf_airquality.csv")  |> 
  filter(name == "Ozone (O3)") |> 
  filter(str_detect(time_period, "2009|2010|2011|2012|2013|2014|2015|2016|2017|2018|2019|2020|2021")) |> 
  mutate(year = str_extract(time_period, "\\d{4}")) |> 
  select(year, data_value)
```


## Histogram of levels of air pollutants by year

```{r}
all_years = sort(unique(c(as.numeric(df_histo_pm2.5$year),
                           as.numeric(df_histo_NO2$year),
                           as.numeric(df_histo_ozone$year))))

combined_fig = plot_ly()


pollutants_data = list(df_histo_pm2.5, df_histo_NO2, df_histo_ozone)
pollutant_names = c("PM2.5", "NO2", "O3")
pollutant_units = c("PM2.5 Concentration (mcg/m3)", "NO2 Concentration (ppb)", "O3 Concentration (ppb)")


for(i in seq_along(pollutants_data)) {

  for(year_value in all_years) {
    year_data = filter(pollutants_data[[i]], year == as.character(year_value))
    combined_fig = combined_fig |>
      add_histogram(data = year_data, 
                    x = ~data_value, 
                    name = as.character(year_value),
                    marker = list(opacity = 0.6),
                    visible = i == 1) 
  }
}

num_years = length(all_years)
buttons = lapply(seq_along(pollutants_data), function(i) {
  visibility = c(rep(FALSE, num_years * (i - 1)), 
                 rep(TRUE, num_years), 
                 rep(FALSE, num_years * (length(pollutants_data) - i)))
  list(method = "update",
       args = list(list("visible" = visibility),
                   list("title" = paste(pollutant_names[i], "Concentration"),
                        "xaxis.title" = pollutant_units[i])),
       label = pollutant_names[i])
})

combined_fig = combined_fig |>
  layout(title = "Comparison of Pollutant Concentrations",
         barmode = "overlay",
         xaxis = list(title = "Concentration"),
         yaxis = list(title = 'Count of Measurements'),
         updatemenus = list(list(type = "dropdown", buttons = buttons)))

combined_fig
```

## Boxplots of levels of air pollutants by year 

```{r}
add_yearly_boxplots <- function(data, years, name_prefix, visible) {
  for(year_value in years) {
    year_data = filter(data, year == as.character(year_value))
    combined_boxplot_fig <<- combined_boxplot_fig %>%
      add_trace(data = year_data, 
                y = ~data_value, 
                type = 'box',
                name = paste(name_prefix, year_value),
                visible = visible)
  }
}


combined_boxplot_fig = plot_ly()


add_yearly_boxplots(df_histo_pm2.5, all_years, "PM2.5", TRUE)

add_yearly_boxplots(df_histo_NO2, all_years, "NO2", FALSE)
add_yearly_boxplots(df_histo_ozone, all_years, "O3", FALSE)


buttons = lapply(seq_along(pollutants_data), function(i) {
  visibility = c(rep(i == 1, num_years), rep(i == 2, num_years), rep(i == 3, num_years))
  list(
    method = "update",
    args = list(
      list("visible" = visibility),
      list(
        "title" = paste(pollutant_names[i], "Concentration"),
        "yaxis.title" = pollutant_units[i]
      )
    ),
    label = pollutant_names[i]
  )
})


combined_boxplot_fig = combined_boxplot_fig %>%
  layout(
    title = "Comparison of Pollutant Concentrations (Boxplots)",
    yaxis = list(title = pollutant_units[1]), 
    updatemenus = list(list(type = "dropdown", buttons = buttons))
  )

combined_boxplot_fig

```

# Disease EDA

## Histogram of respiratory related hospitalizations
