---
title: "Air Quality and Health in NYC"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---


# About

It is well established that long term exposure to poor air quality is associated with negative health outcomes, particularly in urban areas with high population density and vehicle traffic. While New York City has relatively clean air when compared to many other urban environments, it still attributes thousands of deaths to poor air quality annually. While current legislation is in place to improve air quality, more research is needed to determine which locations are most heavily impacted by poor air quality. In particular, pollutants such as nitrogen dioxide, ozone, and other fine particles (PM 2.5) pose significant health hazards and are associated with a number of respiratory diseases in high enough quantities. This project examines the association between air quality and public health in New York City with the goal of showing where interventions are needed most.


Sources (will create a tidy citation later): 
https://www.nyc.gov/site/doh/about/press/pr2023/new-stats-show-nyc-continues-to-clear-the-air.page
