---
title: "Air Quality and Health in NYC"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

# Project Report 
 
## **Introduction** 

### Background
Public health and overall community well-being are impacted by environmental factors such as the concentration of air pollutants in an area. While recent policy and public sentiment has lowered the emissions of air pollutants in many urban environments, air pollution still poses a threat to millions annually. This is especially true in urban environments with large amounts of industry and vehicle emissions. New York City is a great example of an urban setting where air pollution has been [decreasing](https://www.nyc.gov/site/doh/about/press/pr2022/earth-day-new-report-on-nyc-air-quality.page#:~:text=NYC%20Community%20Air%20Survey%20Findings%20Between%202009%20and%202020,ozone%20levels%20have%20remained%20stable.) over the past decade, but some regions still remain vulnerable. Thus, more research is required to determine where future initiatives should be targeted to best improve New York City air quality. This project aims to review the geographic and temporal distribution of air pollutants to determine if recent air pollution trends contribute to respiratory related hospitalizations and to determine which regions are experiencing the worst air pollution. 

While there are countless air pollutants, key pollutants of public health concern include: carbon monoxide (CO), ozone (O3), nitrogen dioxide (NO2), and  fine particulate matter 2.5 (PM2.5) [(WHO)](https://www.who.int/health-topics/air-pollution#tab=tab_1). As a colorless and odorless gas, CO poses a great health risk when inhaled in large amounts. Majority of CO levels are attributed to machinery that use fossil fuels such as vehicles and gas space heaters [(EPA)](https://www.epa.gov/co-pollution/basic-information-about-carbon-monoxide-co-outdoor-air-pollution). Some air pollutants, such as, ground-level ozone are created via a chemical reaction between nitrogen oxides (NO_x), volatile organic compounds (VOC), and sunlight [(EPA)](https://www.epa.gov/ground-level-ozone-pollution/ground-level-ozone-basics). During summer months O3 levels tend to peak due to regions with elevated NOX emissions. Areas with high traffic levels, NO_x reacts to ground-level O3 showing a reduction of O3 concentrations. Moreover, areas such as city centers or areas with NO_x emission show lower O3 levels [(EHDP)](https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/key-topics/airquality/nyccas/). PM2.5, a prevalent air pollutant, originates from both outdoor and indoor environments. Outdoor sources comprise of vehicle emissions, gas, and fires, while indoor contributors encompass tobacco smoke, candle combustion, and oil lamps [(NYSD)](https://www.health.ny.gov/environmental/indoors/air/pmq_a.htm). 

Long term and short term exposure to the pollutants discussed above is associated with a number of health concerns such as respiratory diseases and heart attacks [(EPA)](https://www.epa.gov/report-environment/air#:~:text=Air%20pollution%2C%20whether%20indoors%20or,respiratory%20symptoms%2C%20and%20premature%20mortality.). For example, high levels of O3 can pose a great risk with those suffering from asthma [(EPA)](https://www.epa.gov/ground-level-ozone-pollution/ground-level-ozone-basics). According to the New York State Department of Heath, in-taking high levels of PM2.5 can increase the risk for health problems [(NYSD)](https://www.health.ny.gov/environmental/indoors/air/pmq_a.htm). 

### Motivation 
The need for a comprehensive analysis and sustainable solutions for the increase of air pollutants is needed. The motivation behind this project stems from the potential effects pollutants may have on human health. We aim to understand the association between air quality and public health in New York City, to identify where interventions are needed. 
?? Remove maybe keep in intro??

### Initial Questions
- What are the air quality levels in New York City?
- Which areas in New York City have more prominent air pollutants? 
- How is air quality associated to the incidence of respiratory diseases in an area?

### Related Work 
In a study evaluating the potential decrease in greenhouse gas (GHG) emissions in relation to air quality and public health in NYC, the suggested policy measures may result in an annual reduction of 160 to 390 deaths attributed to PM2.5. Neighborhoods characterized by higher poverty levels showed a more pronounced health gain [Johnson, S. 2020](https://pubs.acs.org/doi/10.1021/acs.est.0c00694). 

In a study focusing on PM2.5 levels, the potential health benefits for adults and children were assessed. Outcomes such as preterm birth, low birthweight, infant mortality, asthma incidence, hospital admissions, emergency visits, and autism spectrum disorder were considered. A estimated 23% improvement in PM2.5 was calculated, thus leasing to avoided illness cases and death. Furthermore, for the period 2021-2025, the estimated associated economic benefit ranged from \$31.8 billion and \$77 billion [Perera, F. 2021](https://www.sciencedirect.com/science/article/pii/S0013935120314523?via%3Dihub).

Ambient PM2.5 attributed deaths increased from 3.5 million in 1990 to 4.2 million in 2015. In 2015, the fifth-ranking cause of global deaths was ambient PM2.5 [PM2.5 related deaths](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5439030/). In a study following the PM2.5 concentration in NYC from 2015-2020, similar decrease levels between January and May were observed. There was less air pollutant in 2020 that could have been due to the government shutdown during the corona virus pandemic could not be confirmed[COVID shutdown](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7314691/#bb0010). 

## **Methods and Exploratory Analysis** 
### Data Sources
The initial air quality dataset was obtained from [NYC Open Data](https://data.cityofnewyork.us/Environment/Air-Quality/c3uy-2p5r), showing comprehensive  information on air pollutants in NYC from 2008 to 2021. The year range 2010 to 2021 was chosen for analysis. A subsequent air quality data set was obtained from [EPA](https://www.epa.gov/outdoor-air-quality-data/download-daily-data). 
[add info about dataset]

The initial health data set obtained from [NYC OpenData](https://data.cityofnewyork.us/Health/Emergency-Department-Visits-and-Admissions-for-Inf/2nwg-uqyg), specified emergency department visits, admissions and visits related to influenza-like and/or pneumonia illness, categorized by the modified ZIP code. A secondary disease data set from [NYC Health](https://a816-health.nyc.gov/hdi/epiquery/visualizations?PageType=ps&PopulationSource=Syndromic) detailed the number of hospitalizations attributed to asthma, diarrhea, influenza-like illness, respiratory diseases, and vomiting for each zip code. The data collection period occurred during 2016 to early 2023. 

Additionally, a geographic location dataset was used to provide more precise location data for observations in both air quality datasets. These were used in the map making process as well as for statistical analyses later. 

?? add more here i think ??


### Data Cleaning 
Two air quality and two disease data sets were obtained for analysis. [AIR QUALITY (SEASONAL) ONE CLEANING]. [AIR QUALITY (DAILY)]. 
Two disease data sets. [1] and [2]

### Exploratory Analysis and Visualizations

O3, PM2.5, and NO2 were the air pollutants chosen for our descriptive and statistical analysis. 

#histogram/boxplot seasonal air quality from 2009-2021
An interactive histogram showing each air pollutant concentration overlaid by year, from the years 2009-2021, was constructed to depict frequency distribution and central tendency. Additionally, the spread, central tendency, and presence of outliers were shown in an interactive box plot based on air pollutant and year. PM2.5 and NO2 concentrations continuously declined from 2009 to 2021, as evident on the layered histogram and box plots. PM2.5 showed a steady decrease in concentration, with the lowest median concentration exhibited in 2020.O3 concentrations initially increased from 2010 to 2016, but seemed to stabilize around 30 ppb with observed measurement decreases from 2017 to 2021

#heatmaps of seasonal air quality from 2009-2021
A heat map of the air pollutants with a year selector was constructed to monitor and understand the air quality in NYC. High concentrations of the selected pollutant were indicated by red and maroon, while lower concentrations were shown in green. The heat map revealed distinct spatial and temporal patterns of O3. Lower Manhattan showed a steady increase of O3 levels from 2009 to 2021. Outer boroughs such as Brooklyn showed consistent concentrations of O3 from 2009 to 2021.Comparing 2009 to 2021, the levels in each area show a decline in PM2.5 levels. Additionally, the layered PM2.5 map shows a greater amount of PM2.5 levels in lower Manhattan throughout the years.NO2 also displayed a decrease in concentration however it was less noticeable. O3 concentrations displayed a different trend. 

#time series daily counts air qual and daily of disease 
Time series plot in regards to daily ER visit and disease counts were generated, showing that asthma and respiratory diseases did not have a seasonal pattern. However, pneumonia ER visits did peak during the winter months. Similarly, time series plots were created for daily air concentrations. Trend and seasonal patterns of CO, O3, and N02 showed oscillations throughout the year. Specifically, O3 showed the a greater difference and reached high levels during the summer month a opposed to NO2 which peaked in the winter. PM2.4 should a steady concentration trend and did not display seasonal patterns. 

#boxplot of daily air pollutants by borough
The frequency distribution of daily air pollutant concentrations in regard to borough was shown in boxplots. NO2 and PM2.5 showed consistent daily medians throughout each borough. O3 showed a slightly elevated daily concentration median in Staten Island compared to other boroughs. 

#time series on daily air pollutant by neighborhood 
In the context of these time series plots, the daily mean measurement of each pollutant, categorized by neighborhoods, was derived and depicted as a distinctive line. Coherent patterns were observed for each pollutant in these neighborhoods. NO2 displayed its pinnacle reach during the winter and spring transitions, where as O3 sowed its highest vales in the summer months. These visual representation shows and highlights the nuanced temporal fluctuation between the pollutants. 


## **Statistical Results** 
Cross correlation analysis was used to examine the relationship between O3 and pneumonia ER visits. From the cross-correlation plots, the positive and negative correlations determined the lag between O3 levels and and pneumonia ER visits was about 117 days. The lag was added as an additional predictor in the linear regression model.

## **Discussion and Conclusions**
### Findings


- Are they what you expect? 
- What insights into the data can you make?


### Limitations

Several challenges arose in the analysis related to data processing. The datasets had significant constraints, including limited data, temporal dimensions, and location misalignment. The limited data potentially impacted our overall findings. The air quality datasets had different observation frequencies, with one being seasonal and the other daily. Health outcomes affected by air pollutants  may be misrepresented due to the lack of hospital information in areas of high pollutants. Lastly, with only 3,000 observations available from an original data set of 188,000 observations, there was a substantial reduction in sample size data.

### Future Implications




