---
title: "InteractiveMaps"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
    code_folding: hide
---

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(leaflet)
library(plotly)
library(glue)
library(leaflet.extras)
```

## 2009-2021: Ozone levels (O3)

```{r, echo = FALSE, message = FALSE, warning = FALSE}
air_df = read_csv("data/cleaned_data/air_quality_zips.csv")
df_air_geo = 
  read_csv("data/cleaned_shapes/zip_shapes.csv") |> 
  select(zip, intptlat10, intptlon10) |> 
  left_join(read_csv("data/cleaned_data/air_quality_zips.csv"), by = "zip") |> 
  mutate(lat = intptlat10,
         lon = intptlon10) |> 
  select(-intptlat10, -intptlon10)

o3_data = df_air_geo |> 
  filter(str_detect(name, "Ozone") & str_detect(name, "\\(")) |> 
  mutate(start_date = as.Date(start_date, format = "%m/%d/%Y"),
         year = year(start_date),
         name = str_remove(name, "(due to).*")) |> 
  select(zip, name, measure, measure_info, year, data_value, borough, lat, lon) |> 
  group_by(zip, name, year, lat, lon) |> 
  summarize(zipmean = mean(data_value)) 

# Create yearly dataframes
yearly_data_frames <- list()
for (k in 2009:2021) {
  year_data = o3_data |> 
    filter(year == k)
  df_name = paste0("o3_", k)
  assign(df_name, year_data)
  yearly_data_frames[[as.character(k)]] = year_data
}

pm25_data = df_air_geo |> 
  filter(str_detect(name, "Fine")) |> 
  mutate(start_date = as.Date(start_date, format = "%m/%d/%Y"),
         year = year(start_date),
         name = str_remove(name, "(due to).*")) |> 
  select(zip, name, measure, measure_info, year, data_value, borough, lat, lon) |> 
  group_by(zip, name, year, lat, lon) |> 
  summarize(zipmean = mean(data_value))


palette <- c("#39FF14", "#FFFF33", "#FF7F00", "#E31A1C", "#9F0000", "#660000")
legend <- c("15-20", "20-25", "25-30", "30-35", "35-40", ">40")


m = leaflet() |> addTiles() 

year_i = unique(o3_data$year)
for(year in year_i) {
  
  
  yeardata = o3_data[o3_data$year == year,]
  
  
  label_text <- glue(
    "<b>Zipcode: </b> {yeardata$zip}<br/>",
    "<b>Year: </b> {yeardata$year}<br/>",
    "<b>Mean: </b> {yeardata$zipmean}<br/>") |> 
    lapply(htmltools::HTML)
  
  
  m = m |>
    addCircleMarkers(data = yeardata, lng = ~lon, lat = ~lat, radius = .5, opacity = 0.8, 
                     color = ~ifelse(between(zipmean, 15, 20), "#39FF14", 
                                     ifelse(between(zipmean, 20.1, 25), "#FFFF33", 
                                            ifelse(between(zipmean, 25.1, 30),"#FF7F00",
                                                   ifelse(between(zipmean, 30.1, 35), "#E31A1C",
                                                          ifelse(between(zipmean, 35.1, 40), "#9F0000", "#660000"))))),
                     label = label_text, group = as.character(year))
}

m = m |> 
  addHeatmap(data = yeardata,lng = ~lon, lat = ~lat, 
             intensity = 2, blur = 5, max = 4, radius = 10, 
             group = "Heatmap Overlay") |> 
  addLegend(labels = legend, colors = palette, title = "Ozone levels") |> 
  addLayersControl(overlayGroups = "Heatmap Overlay",
                   baseGroups = year_i,
                   options = layersControlOptions(collapsed = FALSE)) 

m
```
