---
title: "prelim_disease_eda"
author: "Lupe Antonio"
date: "12/6/2023"
output: html_document
---

```{r setup, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(janitor)
```

```{r}
#loading solo disease 
disease_solo <- read_csv(here::here('data/cleaned_data/disease_solo.csv'))

#loading disease data
disease_zip <- read_csv(here::here('data/cleaned_data/disease_zip.csv'))

#loading alt/new air quality data
air_quality <- read_csv(here::here('data/cleaned_data/alt_air_data.csv'))


#loading older air quality data
air_quality_zips <- read_csv(here::here('data/cleaned_data/air_quality_zips.csv'))





#loading disease + air data
air_quality_disease <- read_csv(here::here('data/cleaned_data/air_quality_disease.csv'))


#loading previously joined data w extra disease data
air_disease <- read_csv('data/cleaned_data/final_airqualdis.csv')


#lots of NAs for most recently joined disease data
```


```{r}
#loading other datasets to preview & troubleshoot
pollutant_per_neighb <- read_csv(here::here('data/cleaned_data/pollutant_per_neighborhood.csv'))


#cleaning second disease data
joined_resp <- read_csv(here::here('data/cleaned_data/joined_respiratory.csv'),
                        col_types = cols(
                          `date` = col_date(format = '%m/%d/%y'))) %>%
  separate(date, into = c('year', 'month', 'day')) %>%
  rename(zip_code = zip) %>%
  filter(!(zip_code == 'Citwide'),
         !(zip_code == '88888'),
         age_group == 'All age groups') %>%
  mutate(month = case_when(
    month == '01' ~ 'January',
    month == '02' ~ 'February',
    month == '03' ~ 'March',
    month == '04' ~ 'April',
    month == '05' ~ 'May',
    month == '06' ~ 'June',
    month == '07' ~ 'July',
    month == '08' ~ 'August',
    month == '09' ~ 'September',
    month == '10' ~ 'October',
    month == '11' ~ 'November',
    month == '12' ~ 'December'),
    
    year = as.integer(year),
    zip_code = as.double(zip_code))
```


```{r}
#joining both disease datasets (left_join)
left_joined <- left_join(disease_zip, joined_resp, by = c('zip_code', 'year', 'month', 'day'))
```

```{r}
left_joined[!complete.cases(left_joined), ]
```



```{r}
#joining 2nd option (full_join)
full_joined <- full_join(disease_zip, joined_resp, by = c('zip_code', 'year', 'month', 'day'))
```


```{r}
#exploring NAs in joined datasets
anti_join(left_joined, full_joined, by = c('zip_code', 'year', 'month', 'day'))
#left_join is ok.
```

```{r}
#data in full_joined that are not in left_join
anti_full <- anti_join(full_joined, left_joined)
```

```{r}
#178 unique zip codes
unique(disease_zip$zip_code)
```

```{r}
unique(joined_resp$zip_code)
```


```{r}
unique(anti_full$zip_code)
```

Notes:

Zipcodes in second disease that were not included in merging bc no data for it in first disease

- 10271 (zero counts throughout all years) (299 rows)

- 10278 (zero counts throughout) (879 rows)

- 10279 (zero counts throughout) (124 rows)

- 



10464


```{r}
joined_resp %>%
  filter(zip_code == '10271')
```


```{r}
joined_resp %>%
  filter(zip_code == '10464')
```


```{r}
disease_zip %>%
  filter(zip_code == '10464')
```


```{r}
anti_join(disease_zip, joined_resp) %>%
  filter(zip_code == '10464')
```


```{r}
anti_join(joined_resp, disease_zip, by = c('zip_code', 'month', 'day', 'year')) %>%
  filter(zip_code == '10464')
```



```{r}
anti_full %>%
  filter(zip_code == '10464')
```


