---
title: "EDA on Daily Air Quality Data"
author: "Gustavo Garcia-Franceschini"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(sfheaders)
```

# UHF Air Quality

```{r uhf_airquality}
df_air = read_csv(here::here("data/cleaned_data/uhf_airquality.csv"))

zip_shapes = read_sf(dsn = here::here("raw_shapes/"), 
                     layer = 'tl_2019_us_zcta510') %>% 
  rename(zip = ZCTA5CE10)

air_shapes = read_sf(dsn = here::here("raw_shapes/"), layer = "UHF42") %>%
  filter(id != "0") %>%
  st_transform(crs= st_crs(zip_shapes)) %>%
  rename(geo_join_id = id) %>%
  mutate(geo_join_id = as.numeric(geo_join_id))

df_air = df_air %>%
  left_join(air_shapes) %>%
   mutate(x_center = map_dbl(geometry, ~st_point_on_surface(.x)[[1]]),
         y_center = map_dbl(geometry, ~st_point_on_surface(.x)[[2]]),
         intplon10 = x_center, intplat10 = y_center)
```

# Alt Air Quality

```{r daily_air}
daily_air = read_csv(here::here("data/cleaned_data/alt_air_data.csv"))
```

# Visualization

```{r}
daily_air %>%
  group_by(site_name, pollutant) %>%
  summarize(x = mean(x), y = mean(y))  %>%
  ggplot() + geom_sf(data = df_air, aes(geometry = geometry)) +
  geom_point(aes(x = x, y = y, color = pollutant), alpha = 0.75) + theme_void()
```

# Points in each neighborhood

```{r}
daily_air = daily_air %>%
  st_as_sf(coords = c("x", "y"), crs = st_crs(zip_shapes))
```

```{r}
geo_joins_sites = st_join(daily_air, air_shapes, join = st_within)  %>%
  select(zip_code, site_name, geo_join_id, pollutant) %>%
  group_by(zip_code, site_name, pollutant) %>%
  summarize(geo_join_id = mean(geo_join_id))
```

```{r}
geo_join_neighborhoods = df_air %>%
  group_by(geo_place_name) %>%
  summarize(geo_join_id = mean(geo_join_id))
```

```{r}
left_join(geo_joins_sites, geo_join_neighborhoods) %>%
  select(zip_code, site_name, pollutant, geo_place_name) %>%
  write_csv(here::here("data/cleaned_data/pollutant_per_neighborhood.csv"))
```